"""Cuentos de Luma (fórmula fábula, sep-2026). En cada capítulo, la opción [0] es la tentación.

TARGET dice en qué letra queda la tentación de cada capítulo. Cada opción lleva
(label, título, continuación, prompt de imagen[, moraleja del final]).
"""

TARGET = {
    "luma-faro-mareas": ["a", "c", "b", "c"],
    "luma-isla-barcas": ["b", "a", "c", "a"],
    "luma-arrecife-cristal": ["c", "b", "a", "b"],
}
THREAD = {"luma-faro-mareas": "brillo", "luma-isla-barcas": "tino", "luma-arrecife-cristal": "concha"}

BRILLO = "Brillo the seagull"
ERMO = "Don Ermo the hermit crab"
TINO = "Tino the otter"
NACAR = "Nacar the sea turtle"
URRACA = "the magpie"
LUMA = "Luma"

STORIES = {
    "luma-faro-mareas": {
        "shell": ["La Gaviota de las Plumas Brillantes", "Una gaviota muy simpática y un cangrejo gruñón. ¿A quién creerá Luma?",
                  "el faro de las mareas", "las barcas necesitan la luz del faro antes de que llegue la niebla"],
        "lesson": "Las apariencias engañan.",
        "tail": "stone lighthouse on a rocky coast at dusk, fishing boats on the sea",
        "cover": f"{LUMA} stands at the foot of a tall stone lighthouse at dusk, a handsome shiny white seagull ({BRILLO}) smiles charmingly on her left, while a grumpy old hermit crab ({ERMO}) frowns from a rock on the right",
        "quiz": [["¿Quién avisó de que venía la niebla?", "Don Ermo, el cangrejo", "Brillo, la gaviota", "Un pescador"],
                 ["¿Qué quería Brillo en realidad?", "Las sardinas de las barcas", "Aprender a cantar", "Encender el faro"]],
        "titles": ["Una gaviota muy simpática", "La campana en la niebla", "Plumas en la escalera", "Una sombra en el muelle", "Lo que dicen, no cómo se ven"],
        "texts": [
            "Luma cuida el faro de las mareas. Esta noche vuelven las barcas de pesca. Una gaviota de plumas brillantes se posa a su lado: —Soy Brillo. ¡Qué guardiana tan lista!\n\nDesde una roca, un cangrejo viejo gruñe: —Huele a niebla. Enciende la luz temprano. Luma arruga la nariz. ¡Qué cangrejo tan gruñón!",
            "La niebla llega despacio, como una sábana gris. Brillo sonríe: —No enciendas la luz, que molesta a los peces.\n\nPero Luma ve algo raro: la gaviota no deja de mirar las cestas de sardinas de las barcas. Allá lejos, suena la campana de un barco perdido.",
            "Luma sube corriendo al faro. ¡La caja de cerillas no está! Solo encuentra plumas blancas en el suelo.\n\nDon Ermo sube detrás, paso a paso, con su concha a cuestas. —Yo guardo una piedra de chispa —dice—. Pero pesa mucho para mí.",
            "¡La luz se enciende! Su rayo corta la niebla y las barcas giran hacia el puerto. En el muelle, una sombra blanca se acerca a las cestas de sardinas.\n\nEs Brillo, con las cerillas escondidas bajo el ala. Los pescadores todavía no la han visto. ¿Qué hará Luma?",
            "Las barcas llegan sanas, con sus cestas llenas. Brillo se va volando sin una sola sardina.\n\nLuma se sienta junto a Don Ermo. —Perdón por llamarte gruñón —le dice. El cangrejo casi sonríe. Desde esa noche, Luma escucha lo que dicen, no cómo se ven.",
        ],
        "scene_prompts": [
            f"Wide shot at the top gallery of a stone lighthouse at dusk: a handsome shiny white seagull ({BRILLO}) lands next to {LUMA}, flattering her with a charming smile, while far below on a rock a grumpy old hermit crab ({ERMO}) waves a claw in warning; {LUMA} wrinkles her nose at the crab",
            f"Thick grey fog rolls over the sea at night; {BRILLO} stands on the lighthouse rail staring greedily at baskets of sardines on the fishing boats below, while {LUMA} watches the seagull, suspicious",
            f"Close-up inside a lighthouse lantern room: an empty open matchbox and white feathers on the floor, {LUMA} kneels and stares at the feathers, surprised",
            f"Night harbour lit by the bright beam of the lighthouse cutting through the fog, fishing boats come in, on the pier {BRILLO} sneaks toward the sardine baskets with a matchbox tucked under her wing",
            f"Warm morning on the rocks by the lighthouse: {LUMA} sits beside {ERMO} and smiles kindly at him, the grumpy crab almost smiles back, calm sea",
        ],
        "chapters": [
            [
                ("Hacer caso a Brillo, que es tan simpática.", "El baile de Brillo",
                 "Luma se queda viendo el baile de Brillo. ¡Qué plumas! ¡Qué vueltas! Cuando mira el mar, la niebla ya tapa las olas.\n\nLa gaviota no deja de mirar las cestas de sardinas de las barcas. Allá lejos, suena la campana de un barco perdido.",
                 f"{BRILLO} dances and twirls showing off her shiny feathers on the lighthouse gallery while {LUMA} watches delighted and claps, behind them grey fog swallows the sea",
                 "Una sonrisa bonita no siempre dice la verdad."),
                ("Preguntarle al cangrejo por qué huele a niebla.", "El olfato de Don Ermo",
                 "—Me llamo Don Ermo —gruñe el cangrejo—. La niebla huele a sal mojada. Luma lo huele también. ¡Tiene razón!\n\nPero Brillo la llama con voz dulce, sin dejar de mirar las cestas de sardinas. Allá lejos, suena la campana de un barco perdido.",
                 f"{LUMA} kneels on the rocks to talk with {ERMO}, who sniffs the air and points at the sea with his claw, {LUMA} sniffs too, curious"),
                ("Subir a mirar el mar desde lo alto del faro.", "Desde lo alto",
                 "Desde lo alto, Luma ve una sábana gris que avanza sobre el mar. ¡Niebla! Abajo, Brillo da vueltas junto al muelle.\n\nLa gaviota no mira el mar: mira las cestas de sardinas de las barcas. Allá lejos, suena la campana de un barco perdido.",
                 f"High angle from the top of the lighthouse: {LUMA} holds the railing and looks out at a wall of grey fog advancing over the sea, determined"),
            ],
            [
                ("Escuchar la canción de Brillo un ratito más.", "Una canción muy larga",
                 "Brillo canta tan bonito que Luma cierra los ojos. ¡Tilín, tilín!, insiste la campana. Luma despierta y corre al faro.\n\n¡La caja de cerillas no está! Solo hay plumas blancas en el suelo. Don Ermo llega detrás: —Tengo una piedra de chispa, pero pesa mucho.",
                 f"{LUMA} sits on the lighthouse steps with her eyes closed, dreamy, while {BRILLO} sings to her with musical notes, the fog grows thick behind them",
                 "Quien te distrae, a veces quiere algo."),
                ("Seguir la mirada de Brillo hasta las cestas.", "Lo que mira Brillo",
                 "Luma sigue la mirada de Brillo: ¡las sardinas! Algo no cuadra. Corre al faro para encender la luz.\n\n¡La caja de cerillas no está! Solo hay plumas blancas en el suelo. Don Ermo llega detrás: —Tengo una piedra de chispa, pero pesa mucho.",
                 f"Over-the-shoulder shot: {LUMA} follows the gaze of {BRILLO} down to baskets full of silver sardines on a fishing boat, {LUMA} narrows her eyes, thoughtful"),
                ("Llamar a Don Ermo para que la ayude.", "Un cangrejo en la escalera",
                 "—¡Don Ermo, ayúdeme! —grita Luma. El cangrejo sube paso a paso, gruñendo, mientras Brillo se aleja volando.\n\nArriba, ¡la caja de cerillas no está! Solo hay plumas blancas en el suelo. —Tengo una piedra de chispa —dice Don Ermo—, pero pesa mucho.",
                 f"{LUMA} calls down the spiral stairs of the lighthouse with her hands around her mouth, {ERMO} climbs the steps slowly carrying his shell"),
            ],
            [
                ("Buscar a Brillo para pedirle las cerillas.", "La gaviota que no sabía nada",
                 "Luma baja a buscar a Brillo. —¿Cerillas? Ni idea —dice la gaviota, y esconde el ala. Luma pierde un tiempo precioso.\n\nAl fin, Don Ermo y ella encienden la luz con la piedra de chispa. Las barcas llegan. Y Brillo se acerca a las cestas de sardinas.",
                 f"On the foggy pier {LUMA} asks {BRILLO}, who shrugs innocently while hiding a matchbox under her wing",
                 "Antes de confiar, fíjate en lo que hacen."),
                ("Mirar bien las plumas del suelo.", "Plumas de gaviota",
                 "Luma mira las plumas: son de gaviota. ¡Brillo se llevó las cerillas! No hay tiempo para enfadarse. Con la piedra de Don Ermo, ¡chas!, se enciende la luz.\n\nLas barcas llegan al puerto. Y abajo, Brillo se acerca a las cestas de sardinas.",
                 f"Close-up: {LUMA} holds up a white seagull feather to the lamp light and examines it with a clever look, {ERMO} beside her holds a spark stone"),
                ("Cargar la concha de Don Ermo escaleras arriba.", "Una concha muy pesada",
                 "Luma carga la concha de Don Ermo escaleras arriba. ¡Uf, cómo pesa! El cangrejo saca su piedra y, ¡chas!, se enciende la luz.\n\nLas barcas llegan al puerto, una detrás de otra. Y abajo, Brillo se acerca a las cestas de sardinas.",
                 f"{LUMA} carries {ERMO} in his heavy shell up the lighthouse spiral stairs, straining but smiling, the crab holds on"),
            ],
            [
                ("Creer a Brillo, que dice que solo mira.", "Una voz muy dulce",
                 "—Solo miraba, de verdad —dice Brillo con su voz dulce. Luma duda… y la gaviota se lleva la cesta más grande de un picotazo.\n\nDon Ermo suspira. Luma aprende tarde, pero aprende: las plumas brillantes no hacen buena a una gaviota. Las apariencias engañan.",
                 f"On the harbour pier {BRILLO} flies off with a whole basket of sardines in her beak while {LUMA} stares with her mouth open, {ERMO} sighs",
                 "Las apariencias engañan.", "Las apariencias engañan."),
                ("Enseñar a todos las plumas y las cerillas.", "Las pistas no mienten",
                 "Luma muestra las plumas blancas y la caja de cerillas. Los pescadores entienden todo y cuidan sus cestas. Brillo se va volando, avergonzada.\n\nLuma aprende que las pistas dicen la verdad, aunque una sonrisa diga otra cosa.",
                 f"{LUMA} holds up white feathers and a matchbox to surprised fishermen on the pier, {BRILLO} flies away embarrassed",
                 None, "Las pistas dicen más que una sonrisa."),
                ("Pedir a Don Ermo que cuente lo que vio.", "El testigo gruñón",
                 "Don Ermo cuenta lo que vio desde su roca: Brillo esconde cosas ajenas. Todos le creen, porque siempre dice la verdad, aunque gruña.\n\nLuma lo mira con otros ojos. Un amigo gruñón y sincero vale más que uno bonito y mentiroso.",
                 f"{ERMO} stands on a barrel on the pier and tells the fishermen what he saw, pointing his claw at {BRILLO}, {LUMA} smiles proudly at the crab",
                 None, "Un amigo sincero vale más que uno bonito."),
            ],
        ],
    },
    "luma-isla-barcas": {
        "shell": ["La Barca Perfecta", "Luma quiere la barca más perfecta del mar… y la carrera es mañana.",
                  "la isla de las barcas", "la barca debe estar lista para la carrera de mañana"],
        "lesson": "Mejor hecho que perfecto.",
        "tail": "small sunny island beach with a wooden workshop, calm turquoise sea",
        "cover": f"{LUMA} carefully sands a beautiful unfinished wooden boat on a sunny island beach, while {TINO} laughs as he splashes on a crooked little log raft in the water",
        "quiz": [["¿Qué hizo Tino con su balsa?", "La probó en el agua", "La pintó tres veces", "La dejó en la orilla"],
                 ["¿Qué entraba por la rendija de la barca de Luma?", "Agua", "Arena", "Peces"]],
        "titles": ["Una balsa torcida", "¡Glu, glu!", "La rendija", "¡Preparados, listos…!", "La meta"],
        "texts": [
            "Mañana es la carrera de barcas de la isla. Luma quiere construir la barca más perfecta del mar: lisa, pintada y sin un solo fallo.\n\nTino, la nutria, ya tiene una balsa de troncos. —¡Está torcida, pero flota! —se ríe, y chapotea. Luma frunce el ceño. Torcida no sirve.",
            "Por la tarde, el casco ya está listo. Pero a Luma no le gusta el azul: ¡es demasiado claro! Quiere pintarlo otra vez.\n\nEn la orilla, Tino prueba su balsa. ¡Glu, glu! Entra un poquito de agua. —¡Un agujerito! —dice feliz—. Menos mal que lo probé hoy.",
            "El sol se esconde. La barca de Luma flota, pero por una rendija entra agua. Hay que taparla antes de la carrera.\n\nTino le da un poco de resina. Luma mira su barca y piensa en una bandera con estrellas doradas. ¡Quedaría perfecta!",
            "¡Amanece el día de la carrera! Las barcas esperan en la salida. La de Luma flota, aunque tiene un rayón y la pintura no es perfecta.\n\n—¡Preparados, listos…! —grita la foca del puerto. Luma mira el rayón y duda. ¿Qué hará?",
            "Las barcas cruzan la meta entre olas y risas. Tino chapotea feliz en su balsa torcida.\n\nLuma mira su barca, con su rayón y su azul claro. No es perfecta, pero navega. Y descubre que eso era lo más importante.",
        ],
        "scene_prompts": [
            f"Wide shot of a sunny island beach: {LUMA} frowns while sanding a smooth unfinished wooden boat hull, in the water {TINO} laughs and splashes on a crooked little log raft",
            f"Afternoon on the beach: {LUMA} frowns at the light blue paint of her finished boat hull holding a paintbrush, in the shallow water {TINO} happily points at a tiny leak in his log raft with water bubbling in",
            f"Sunset: {LUMA}'s blue boat floats in the shallows with a thin stream of water leaking in through a crack, {LUMA} kneels in the water looking worried, {TINO} offers her a small pot of pine resin",
            f"Morning race start on the sea: small boats line up at a start rope, {LUMA} sits in her blue boat looking doubtfully at a scratch on its side, {TINO} on his raft beside her, a seal on a rock raises a flag",
            f"Wide shot of boats crossing a finish line of floating buoys, {TINO} cheers on his crooked raft, {LUMA} smiles proudly in her imperfect blue boat",
        ],
        "chapters": [
            [
                ("Lijar la madera hasta que brille.", "Madera como un espejo",
                 "Luma lija y lija hasta que la madera brilla como un espejo. ¡Se le pasa media mañana! Por la tarde, el casco está listo, pero el azul no le gusta.\n\nEn la orilla, Tino prueba su balsa. ¡Glu, glu! —¡Un agujerito! —dice feliz—. Menos mal que lo probé hoy.",
                 f"Close-up: {LUMA} sands a wooden plank over and over, sweating, with a mountain of sawdust around her, the sun already high, {TINO} yawns nearby",
                 "Lo bonito no sirve si no está hecho."),
                ("Pedirle a Tino que le enseñe su balsa.", "Primero que flote",
                 "Tino le enseña su balsa: troncos, cuerda y una vela vieja. —Primero que flote, luego que sea bonita —dice. Por la tarde, el casco de Luma está listo, pero el azul no le gusta.\n\nTino prueba su balsa. ¡Glu, glu! —¡Un agujerito! Menos mal que lo probé hoy.",
                 f"{TINO} proudly shows {LUMA} his crooked raft made of logs, rope and an old patched sail, {LUMA} listens with interest"),
                ("Hacer primero un dibujo sencillo.", "Un dibujo sencillo",
                 "Luma dibuja una barca sencilla y la construye paso a paso. Por la tarde, el casco está listo. Pero el azul no le gusta: ¡es demasiado claro!\n\nEn la orilla, Tino prueba su balsa. ¡Glu, glu! —¡Un agujerito! —dice feliz—. Menos mal que lo probé hoy.",
                 f"{LUMA} sits on the sand drawing a simple boat with a stick, calm and focused, wooden planks ready beside her, {TINO} in the background"),
            ],
            [
                ("Pintar la barca otra vez, más oscura.", "Pintura que no seca",
                 "Luma pinta la barca de azul oscuro. Espera, espera… ¡la pintura tarda en secarse! Al atardecer la pone en el agua, y por una rendija entra agua.\n\nTino le da un poco de resina para taparla. Pero Luma piensa en una bandera con estrellas doradas.",
                 f"{LUMA} repaints her boat dark blue with a big brush, then waits bored with her chin on her hands while the paint dries, {TINO} already sails his raft",
                 "Probar a tiempo evita sustos."),
                ("Probar la barca en el agua, como Tino.", "La prueba del agua",
                 "Luma pone su barca en el agua. Flota… ¡pero por una rendija entra agua! Mejor saberlo hoy que en la carrera.\n\nTino le da un poco de resina para taparla. Al atardecer, Luma piensa en una bandera con estrellas doradas. ¡Quedaría perfecta!",
                 f"{LUMA} pushes her blue boat into the shallow water and discovers a small jet of water leaking through a crack, surprised, {TINO} gives a thumbs up"),
                ("Preguntar a Tino cómo tapó su agujero.", "Resina de pino",
                 "—Con resina de pino —explica Tino, y le regala un poquito. Luma prueba su barca: ¡por una rendija entra agua!\n\nMenos mal que tiene la resina. Al atardecer, Luma piensa en una bandera con estrellas doradas. ¡Quedaría perfecta!",
                 f"{TINO} shows {LUMA} how he sealed his raft with golden pine resin, handing her a small pot, {LUMA} smiles gratefully"),
            ],
            [
                ("Coser la bandera de estrellas antes de nada.", "Una bandera preciosa",
                 "Luma cose la bandera hasta la noche. Queda preciosa, pero la rendija sigue abierta. Tino la ayuda a taparla a toda prisa, y en el apuro la barca se raya.\n\nAmanece el día de la carrera. —¡Preparados, listos…! —grita la foca del puerto.",
                 f"Night by a lantern: {LUMA} sews a blue flag with golden stars, while her boat behind her fills with water through the crack, {TINO} points at it alarmed",
                 "Primero lo importante, después lo bonito."),
                ("Tapar la rendija primero.", "Ni una gota",
                 "Luma tapa la rendija con la resina de Tino. Ya no entra ni una gota. Al guardar las herramientas, la barca se raya un poquito.\n\nAmanece el día de la carrera. La barca flota, aunque no es perfecta. —¡Preparados, listos…! —grita la foca del puerto.",
                 f"Close-up at sunset: {LUMA} carefully presses golden resin into the crack of her blue boat, concentrated, {TINO} holds the lantern"),
                ("Tapar la rendija junto con Tino.", "Una canción de remos",
                 "Luma y Tino tapan la rendija juntos, cantando una canción de remos. Al empujar la barca, se hace un rayón.\n\nAmanece el día de la carrera. La barca flota, aunque no es perfecta. —¡Preparados, listos…! —grita la foca del puerto.",
                 f"{LUMA} and {TINO} seal the boat together, singing with open mouths and music notes in the air, laughing, sunset on the beach"),
            ],
            [
                ("Volver a la orilla para arreglar el rayón.", "El rayón",
                 "Luma rema a la orilla para tapar el rayón. Cuando vuelve, ¡la carrera ya terminó! Tino la saluda con su medalla de concha.\n\nLuma se ríe de sí misma. Una barca perfecta en la orilla no gana carreras. Mejor hecho que perfecto.",
                 f"On the beach {LUMA} polishes a tiny scratch on her boat while far out at sea the other boats already cross the finish line, {TINO} waves a shell medal",
                 "Mejor hecho que perfecto.", "Mejor hecho que perfecto."),
                ("Salir tal como está y remar tranquila.", "Segunda en la meta",
                 "Luma sale tal como está. La barca no es perfecta, pero es fuerte y la probó bien. ¡Llega segunda, justo detrás de Tino!\n\nNadie mira el rayón. Todos miran lo rápido que navega. Luma aprende que lo que se prueba vale más que lo que brilla.",
                 f"{LUMA} rows her blue boat calmly and strongly through the waves, just behind {TINO} on his raft, the finish buoys ahead",
                 None, "Lo que se prueba vale más que lo que brilla."),
                ("Remar al lado de Tino.", "Juntos a la meta",
                 "Luma rema al lado de Tino, riendo con cada ola. Llegan juntos a la meta, mojados y felices.\n\n—Tu balsa torcida es la mejor —le dice Luma. Aprendió que hacer las cosas con un amigo es más divertido que hacerlas perfectas.",
                 f"{LUMA} in her blue boat and {TINO} on his raft row side by side laughing through splashing waves toward the finish",
                 None, "Con un amigo, lo imperfecto también es divertido."),
            ],
        ],
    },
    "luma-arrecife-cristal": {
        "shell": ["La Concha y su Reflejo", "Una concha rosada, un agua que engaña y un regalo para la abuela.",
                  "el arrecife de cristal", "la concha rosada debe llegar a casa de la abuela"],
        "lesson": "Quien todo lo quiere, todo lo pierde.",
        "tail": "clear crystal-blue lagoon with a coral bridge and pink and aqua coral",
        "cover": f"{LUMA} crosses a coral bridge over crystal clear water holding a pink seashell, looking down at a huge shimmering pink shell reflected in the water, {NACAR} swims beside her",
        "quiz": [["¿Para quién era la concha rosada?", "Para la abuela de Luma", "Para Nácar", "Para la urraca"],
                 ["¿Qué era la concha grande del agua?", "El reflejo de la suya", "Una concha mágica", "Un pez rosado"]],
        "titles": ["Un regalo para la abuela", "La concha del agua", "Dos caminos", "Tres piedras brillantes", "Junto a la ventana"],
        "texts": [
            "Luma encuentra en la playa una concha rosada, perfecta para el cumpleaños de su abuela. La guarda en su bolsillo, feliz.\n\nPara volver a casa, debe cruzar el Arrecife de Cristal. Nácar, la tortuga, nada a su lado. —Cuidado —le dice—. Aquí el agua engaña a los ojos.",
            "En medio del puente de coral, Luma se asoma al agua. ¡Allí abajo brilla una concha rosada enorme, mucho más grande que la suya!\n\n—Con esa, mi abuela saltaría de alegría —piensa. Nácar asoma la cabeza y la mira en silencio.",
            "Luma comprende: la concha grande era el reflejo de la suya, agrandado por el agua de cristal. ¡No existía!\n\nYa es tarde y la marea sube. Por el camino corto hay un paso estrecho; por el largo, una vuelta que rodea el arrecife.",
            "Luma llega a casa de la abuela al atardecer. En la puerta, una urraca le ofrece tres piedras brillantes a cambio de su concha.\n\n—Tres cosas valen más que una —dice la urraca. Luma mira su concha rosada, un poco rayada del viaje. ¿Qué hará?",
            "La abuela abre la puerta y abraza a Luma. Afuera, el mar brilla con el último sol.\n\nLuma piensa en la concha grande del agua, que nunca existió. Lo que de verdad importaba era llegar, y llegar con cariño.",
        ],
        "scene_prompts": [
            f"{LUMA} on a sunny beach holds up a pretty pink seashell with a happy smile, beyond her a crystal clear lagoon and a coral bridge, {NACAR} pokes her head out of the water",
            f"{LUMA} kneels in the middle of a coral bridge and leans over the crystal water, amazed, below the surface shimmers a giant pink seashell, {NACAR} watches her quietly",
            f"{LUMA} stands at a fork on the reef as the tide rises, one short path leads to a narrow rocky passage, one long path curves around the reef, {NACAR} beside her",
            f"Sunset at the door of a small seaside cottage: a black and white magpie ({URRACA}) holds out three glittering stones to {LUMA}, who holds her pink seashell, doubtful",
            f"Warm cottage window at sunset: an old grandma hugs {LUMA}, the pink seashell rests on the windowsill, the sea glows outside",
        ],
        "chapters": [
            [
                ("Buscar más conchas, ¡cuantas más, mejor!", "Bolsillos llenos",
                 "Luma llena los bolsillos de conchas: blancas, rotas, con arena… ¡Pesan tanto que casi no puede andar! Las deja y se queda con la rosada.\n\nEn medio del puente de coral, se asoma al agua. ¡Abajo brilla una concha rosada enorme, mucho más grande que la suya!",
                 f"{LUMA} walks bent over with bulging pockets overflowing with seashells, shells spilling onto the sand, funny, {NACAR} laughs in the water",
                 "Quien mucho abarca, poco aprieta."),
                ("Preguntar a Nácar qué quiere decir.", "Mirar dos veces",
                 "—El agua de cristal agranda lo que refleja —explica Nácar—. Mira dos veces antes de creer. Luma asiente, sin entender del todo.\n\nEn medio del puente de coral, se asoma al agua. ¡Abajo brilla una concha rosada enorme, mucho más grande que la suya!",
                 f"{LUMA} sits on the edge of the coral bridge listening to {NACAR}, who explains wisely from the crystal water, {LUMA} holds her pink shell"),
                ("Cruzar despacio por el puente de coral.", "Paso a paso",
                 "Luma cruza despacio el puente de coral, paso a paso, con la concha bien guardada. Nácar nada tranquila a su lado.\n\nEn medio del puente, Luma se asoma al agua. ¡Abajo brilla una concha rosada enorme, mucho más grande que la suya!",
                 f"Wide shot: {LUMA} walks carefully across a narrow coral bridge over crystal water, arms out for balance, {NACAR} swims calmly alongside"),
            ],
            [
                ("Soltar su concha para atrapar la grande.", "¡Plof!",
                 "Luma saca su concha para atrapar la grande… ¡y se le resbala! Plof. Nácar se zambulle y la rescata. La concha grande desaparece: era el reflejo de la suya.\n\nLa marea sube. Hay un camino corto con un paso estrecho y uno largo que rodea el arrecife.",
                 f"{LUMA} reaches down to the water and her small pink seashell slips from her fingers and falls with a splash, {NACAR} dives after it",
                 "No sueltes lo que tienes por lo que parece."),
                ("Mirar bien la concha grande desde otro lado.", "El reflejo",
                 "Luma mira desde el otro lado del puente. La concha grande se mueve igual que la suya. ¡Es su reflejo, agrandado por el agua de cristal!\n\nLa marea sube. Hay un camino corto con un paso estrecho y uno largo que rodea el arrecife.",
                 f"{LUMA} holds her pink seashell over the crystal water and sees its giant magnified reflection moving the same way, she smiles, understanding"),
                ("Preguntarle a Nácar si la ve también.", "Dos veces la misma concha",
                 "—¿Tú la ves? —pregunta Luma. Nácar se ríe: —Veo tu concha dos veces. El agua de cristal la agranda.\n\nLuma se ríe también. La marea sube. Hay un camino corto con un paso estrecho y uno largo que rodea el arrecife.",
                 f"{LUMA} and {NACAR} laugh together on the coral bridge, the turtle points her flipper at the reflection of the pink shell in the water"),
            ],
            [
                ("Ir por el camino corto, ¡sin mirar!", "El paso bajo el agua",
                 "Luma corre por el camino corto. ¡El paso estrecho está bajo el agua! Da la vuelta y, al final, llega más tarde. La concha se raya contra el coral.\n\nAl atardecer, en la puerta de la abuela, una urraca le ofrece tres piedras brillantes a cambio de su concha.",
                 f"{LUMA} runs down a narrow rocky passage and stops short, the passage is flooded by the rising tide, water up to her knees, surprised",
                 "El camino corto no siempre es el más rápido."),
                ("Mirar cómo sube la marea antes de elegir.", "La vuelta larga",
                 "Luma mira la marea: el paso estrecho ya está cubierto. Elige la vuelta larga, y llega justo a tiempo. La concha se raya un poco en el viaje.\n\nEn la puerta de la abuela, una urraca le ofrece tres piedras brillantes a cambio de su concha.",
                 f"{LUMA} stands on a rock watching the tide cover the narrow passage, thoughtful, then points to the long path around the reef"),
                ("Seguir a Nácar, que conoce el arrecife.", "La guía del arrecife",
                 "Luma sigue a Nácar por la vuelta larga. La tortuga conoce cada roca. Llegan al atardecer, con la concha un poco rayada.\n\nEn la puerta de la abuela, una urraca le ofrece tres piedras brillantes a cambio de su concha. —Tres valen más que una —dice.",
                 f"{NACAR} swims ahead through calm water along the reef guiding the way, {LUMA} follows along the shore path, golden evening light"),
            ],
            [
                ("Cambiar la concha por las tres piedras.", "Piedras que se apagan",
                 "Luma cambia la concha por las piedras. Al entrar, las piedras se apagan: ¡eran vidrio mojado! La abuela la abraza igual.\n\n—Quien todo lo quiere, todo lo pierde —le dice con cariño. Luma asiente. Mañana buscará otra concha, y esta vez la cuidará.",
                 f"Inside the cottage {LUMA} looks at three dull grey pebbles in her open hand, disappointed, while an old grandma hugs her kindly, the magpie flies off outside with the pink shell",
                 "Quien todo lo quiere, todo lo pierde.", "Quien todo lo quiere, todo lo pierde."),
                ("Mirar bien las piedras antes de decidir.", "Solo brillan mojadas",
                 "Luma mira las piedras de cerca: brillan solo porque están mojadas. —No, gracias —dice, y entra con su concha.\n\nLa abuela la pone junto a la ventana. Luma aprende que una cosa verdadera vale más que muchas que solo brillan.",
                 f"Close-up: {LUMA} examines three wet stones in the magpie's beak with a clever look, holding her pink seashell safe against her chest",
                 None, "Una cosa verdadera vale más que muchas que solo brillan."),
                ("Darle la concha a la abuela junto a Nácar.", "Un regalo con cariño",
                 "Luma y Nácar le dan la concha a la abuela. —¡Es preciosa! —dice ella, y la pone junto a la ventana.\n\nLuma mira su concha pequeña y sonríe. Aprendió que un regalo hecho con cariño es más grande que cualquier reflejo.",
                 f"At the seaside cottage an old grandma receives the pink seashell from {LUMA} with delight, {NACAR} watches happily from the water's edge",
                 None, "Un regalo con cariño es más grande que cualquier reflejo."),
            ],
        ],
    },
}
