import { BookOpen, ChevronLeft, ChevronRight, Sparkles } from 'lucide-react'
import { useEffect, useState } from 'react'

export type SavedStoryCard = { id: string; title: string; category?: string; subtitle: string; coverUrl: string; updatedAt: string; storyStep: number; isFinished: boolean }
type Props = { stories: SavedStoryCard[]; completed: number; onOpen: (id: string) => void }
const pageSize = 6

export function SavedStoriesPanel({ stories, completed, onOpen }: Props) {
  const [page, setPage] = useState(1)
  const totalPages = Math.max(1, Math.ceil(stories.length / pageSize))
  useEffect(() => setPage((value) => Math.min(value, totalPages)), [totalPages])
  const visibleStories = stories.slice((page - 1) * pageSize, page * pageSize)
  return <section className="saved-stories mx-auto max-w-6xl px-5 pb-16 pt-12 sm:px-8" aria-labelledby="saved-stories-title"><div><h1 id="saved-stories-title">Cuentos del pequeño</h1><p>Sus aventuras guardadas, listas para continuar o releer.</p><p className="mt-3 text-sm font-bold text-[#7b4b11]">{completed} {completed === 1 ? 'cuento terminado' : 'cuentos terminados'}</p></div>{stories.length === 0 ? <div className="saved-empty"><Sparkles size={28} aria-hidden="true" /><b>Aún no creaste un cuento</b><span>La próxima aventura aparecerá aquí.</span></div> : <><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visibleStories.map((story) => <article key={story.id} className="group overflow-hidden rounded-2xl bg-white shadow-[0_14px_32px_rgba(78,56,22,.12)]"><img src={story.coverUrl} alt="" loading="lazy" className="h-44 w-full object-cover transition duration-500 group-hover:scale-105" /><div className="p-5"><span className="inline-flex items-center gap-1 text-xs font-black text-[#9a5b22]"><BookOpen size={14} aria-hidden="true" /> {story.category || 'Aventura mágica'}</span><b className="mt-3 block text-xl leading-tight text-[#161512]">{story.title}</b><p className="mt-2 min-h-10 text-sm text-[#5b574c]">{story.subtitle}</p><small className="mt-3 block text-xs font-bold text-[#7b4b11]">{story.isFinished ? 'Cuento terminado' : `Página ${story.storyStep} de 5`}</small><button type="button" onClick={() => onOpen(story.id)} className="mt-4 inline-flex items-center gap-2 bg-[#ffcf22] px-4 py-3 text-sm font-bold text-[#161512] hover:bg-[#ffe06d]">Abrir cuento</button></div></article>)}</div>{totalPages > 1 && <nav className="mt-8 flex items-center justify-center gap-4" aria-label="Paginación de cuentos"><button type="button" onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={page === 1} className="inline-flex items-center gap-2 px-4 py-3 font-bold disabled:opacity-40"><ChevronLeft size={18} />Anterior</button><span className="text-sm font-bold">Página {page} de {totalPages}</span><button type="button" onClick={() => setPage((value) => Math.min(totalPages, value + 1))} disabled={page === totalPages} className="inline-flex items-center gap-2 bg-[#ffcf22] px-4 py-3 font-bold disabled:opacity-40">Siguiente<ChevronRight size={18} /></button></nav>}</>}</section>
}
