$generator = 'C:/Users/Nick/.agents/skills/generador-local-imagenes/scripts/generar.py'
$output = 'F:/Proyectos/ComfyUI/salidas'
$jobs = @(
  @{Story='faro'; Name='opening'; Seed=201; Prompt='Dramatic close composition on lighthouse balcony: exactly one small white seagull uses its wings to turn the great brass light mirror while Luma watches from stone steps below. Three tiny boats ring bells on dark water outside. Only one girl, Luma; no second Luma, no words, no letters; violet storm sky and rocky harbor of the lighthouse world around.'},
  @{Story='faro'; Name='chapter-1-choice-c'; Seed=202; Prompt='Medium close-up on dock: Luma speaks with ONE elderly fisherwoman with short GREY hair and a weathered tan face, distinctly older than Luma. The fisherwoman points toward a tiny boat ringing a bell near rocks. One Luma only, no second girl, no words, no letters; violet storm sky and rocky harbor of the lighthouse world around.'},
  @{Story='faro'; Name='chapter-2-choice-a'; Seed=203; Prompt='Low angle at the END of wet stone pier: Luma leans toward ONE adult male boat captain with grey beard in a tiny boat near sharp rocks. He points to two other boats behind him. Only one Luma, no extra girls, no words, no letters; violet storm sky and rocky harbor of the lighthouse world around.'},
  @{Story='faro'; Name='chapter-2-choice-c'; Seed=204; Prompt='Close conversation: Luma listens to ONE adult male captain with grey beard aboard his little boat. He gestures at a torn-sail boat and another boat far away. Three colored crystals lie on pier. One Luma only, no extra girls, no words, no letters; violet storm sky and rocky harbor of the lighthouse world around.'},
  @{Story='faro'; Name='chapter-3-choice-a'; Seed=205; Prompt='INTERIOR VIEW only, inside the tall lighthouse, stone spiral staircase filling the frame. Luma climbs the stairs carrying three distinct red blue and gold glass crystals in her arms toward a glowing lamp at top. One Luma only, no other characters, no words, no letters; warm lighthouse interior with glimpse of violet harbor through narrow window.'},
  @{Story='faro'; Name='chapter-3-choice-c'; Seed=206; Prompt='Inside lighthouse lamp room: exactly ONE Luma stands beside an elderly male lighthouse keeper with grey beard and navy coat holding a wrench, and a SECOND different adult male boat captain holding colored crystals. Three people total, one girl only. They repair large mirror together. No words, no letters; warm lamp room over violet rocky harbor.'},
  @{Story='faro'; Name='chapter-4-choice-c'; Seed=207; Prompt='On lighthouse balcony: exactly ONE Luma listens to bell signals from three boats at sea. Beside her ONE elderly male lighthouse keeper with grey beard adjusts three colored crystals. No other girls, no duplicate Luma, no words, no letters; violet storm sky and rocky harbor of the lighthouse world around.'},
  @{Story='isla'; Name='chapter-4'; Seed=301; Prompt='Strong dramatic close view in THICK WHITE SEA FOG: a proud fast wooden sailboat lost near dark rocks rings a bell. Tiny seed boat Brisa in foreground answers with its bell while exactly ONE Luma guides from shore. Two boats, no duplicate Luma, no words, no letters; lush green boat island and turquoise sea around.'},
  @{Story='isla'; Name='chapter-1-choice-a'; Seed=302; Prompt='Close-up: exactly ONE Luma sits INSIDE the tiny wooden seed boat Brisa, holding its side while seeing a basket filled with seeds on the boat floor. Bigger fast boat remains at dock behind. No other girls, no words, no letters; lush green boat island and turquoise sea around.'},
  @{Story='isla'; Name='chapter-1-choice-c'; Seed=303; Prompt='Close conversation on dock: exactly ONE Luma kneels beside tiny wooden seed boat Brisa with a shy face painted on its bow, listening to it. Fast bigger boat waits behind by bell. Only one human girl, no duplicate Luma, no words, no letters; lush green boat island and turquoise sea around.'},
  @{Story='isla'; Name='chapter-2-choice-c'; Seed=304; Prompt='At dock exactly ONE Luma listens to THREE distinct boats: tiny seed boat with baskets, big cargo boat with crates, sleek fast boat with bright sail. Each boat has a different face painted on bow and points along a different water route. No extra humans, no words, no letters; lush green boat island and turquoise sea around.'},
  @{Story='isla'; Name='chapter-3-choice-a'; Seed=305; Prompt='Side view deep within THICK WHITE SEA FOG: exactly ONE Luma rides inside tiny seed boat Brisa with a basket of seeds, heading toward sound of distant lost fast boat bell among dark rocks. Strong fog and danger visible. No duplicate Luma, no words, no letters; lush green boat island and turquoise sea around.'},
  @{Story='isla'; Name='chapter-3-choice-c'; Seed=306; Prompt='At wooden island dock in SEA FOG exactly ONE Luma raises her hand to coordinate THREE different boats ringing THREE separate bronze bells, one after another, making a sound path for lost fast boat. Distinct bells visible. No duplicate Luma, no words, no letters; lush green boat island and turquoise sea around.'},
  @{Story='isla'; Name='chapter-4-choice-b'; Seed=307; Prompt='At foggy island dock exactly ONE Luma and tiny seed boat Brisa wait patiently with sail lowered as THICK WHITE FOG clears to reveal dark rocks; fast boat waits safely beside them. No duplicate Luma, no words, no letters; lush green boat island and turquoise sea around.'},
  @{Story='isla'; Name='chapter-4-choice-c'; Seed=308; Prompt='On island dock exactly ONE Luma organizes THREE DIFFERENT BOATS each ringing its own bronze bell while they take turns leaving on clear safe water routes. Tiny seed boat and big fast boat cooperate, golden bell overhead. No duplicate Luma, no words, no letters; lush green boat island and turquoise sea around.'}
)

foreach ($job in $jobs) {
  $world = if ($job.Story -eq 'faro') { 'faro-portada' } else { 'isla-portada' }
  $storyId = if ($job.Story -eq 'faro') { 'luma-faro-mareas' } else { 'luma-isla-barcas' }
  $target = "$output/$storyId-$($job.Name)-retry.webp"
  if (Test-Path -LiteralPath $target) { continue }
  python $generator --personaje luma --mundo $world --seed $job.Seed --prompt $job.Prompt --out $target
  if ($LASTEXITCODE -ne 0) { throw "Falló $target" }
}
